apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app-green
  namespace: my-node-app
  labels:
    app: my-node-app
    version: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-node-app
      version: green
  template:
    metadata:
      labels:
        app: my-node-app
        version: green
    spec:
      containers:
      - name: my-node-app
        image: "{{ .Values.image.repository }}:{{ .Values.green.image.tag }}"
        ports:
        - containerPort: 3000