apiVersion: v1
kind: Service
metadata:
  name: my-node-app-service
  namespace: my-node-app
spec:
  selector:
    app: my-node-app
    version: {{ .Values.activeVersion }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP